// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'US_EAST_2',
  aws_cognito_identity_pool_id: 'us-east-2_bHIfV0fTm',
  aws_cognito_region: 'US_EAST_2',
  aws_user_pools_id: 'us-east-2_bHIfV0fTm',
  aws_user_pools_web_client_id: '3tg2q67k2s7uf0k2k3vr9mcu3f',
  oauth: {},
};

export default awsmobile;
